Minify and building Ts scripts with webpack
ALM-Rangers/generator-team-services-extension pull request #10
Opened 2017-04-16 16:27 UTC by mikaelkrief

Thank you for your pull request!
By completing this pull request, you agree to the [Contributing License Agreement](https://github.com/ALM-Rangers/Yeoman-extension-code-generator/blob/master/.github/CLA.md).

Fixes # .

**Changes proposed in this pull request:**  
- minify and building Ts scripts
- check Ts scripts syntaxe with tslint
- include webpack package and config
- delete the gruntfile.js and related packages
- update the readme with new and removed package

@ALM-Rangers/Yeoman-extension-code-generator

2017-04-17 11:36 UTC, willsmythe requested changes

2017-04-17 11:36 UTC, willsmythe commented on README.md
> +- [tslint](https://www.npmjs.com/package/tslint)  : npm install -g tslint
We need to reduce the number of pre-reqs the user must install. Only Node, Yeoman, and this generator package should be required. The rest can be listed as dev dependencies. NPM scripts can find the executables for dependencies, so "TFX" and "tsc" don't even need to be globally installed to be used.

2017-04-21 19:31 UTC, willsmythe approved these changes

2017-04-21 19:31 UTC, willsmythe commented on generators/hub/templates/static/index.html
> +                 VSS.notifyLoadSucceeded();
Were you getting timeout errors from VSTS because this content was taking awhile to load?

2017-04-21 19:31 UTC, willsmythe commented on generators/hub/templates/package.json
> +    "build": "npm run lint && npm run clean && mkdir dist && webpack --progress --colors --config webpack.config.js --output-path ./dist -p",
Are you required to run "mkdir" .. I'd expect webpack to create it if needed. Also, "mkdir" likely doesn't work on other platforms (e.g. Linux).

2017-04-21 19:31 UTC, willsmythe commented on generators/widget/templates/package.json
> +    "build": "npm run lint && npm run clean && mkdir dist && webpack --progress --colors --config webpack.config.js --output-path ./dist -p",
See earlier comment.

2017-04-23 15:06 UTC, wpschaub approved these changes

2017-04-23 15:06 UTC, merged