Update Generator Name
ALM-Rangers/generator-team-services-extension pull request #5
Opened 2017-03-24 14:56 UTC by mikaelkrief

Thank you for your pull request!
By completing this pull request, you agree to the [Contributing License Agreement](https://github.com/ALM-Rangers/Yeoman-extension-code-generator/blob/master/.github/CLA.md).

**Changes proposed in this pull request:**  
- Update the generator name to : team-services-extension (package.json, tests,index.js)
- update the welcome message
- delete xunit.xml

2017-03-24 16:11 UTC, wpschaub commented
Mikael, can we drop the obj folders in the templates and ignore the vs folder? It "seems" that it's not needed and adds noise.

2017-03-24 20:16 UTC, willsmythe requested changes

2017-03-24 20:16 UTC, willsmythe commented on README.md
> +﻿# Yeoman-extension-code-generator
This L1 should be friendlier, maybe: `Team Services Extension Generator`

2017-03-24 20:16 UTC, willsmythe commented on README.md
> +**generator-team-services-extension** is [Yeoman](http://yeoman.io/) generator that create an extension for Visual Studio Team Services or Team Foundation Server.
" .. is **a** Yeoman generator that **creates** an extension .. "

2017-03-24 20:16 UTC, willsmythe commented on package.json
> +  "description": "Team Foundation Server and Team Services extension code generator",
`Yeoman generator for Team Services and Team Foundation Server extensions`  ?

2017-03-24 20:25 UTC, wpschaub commented on README.md
> +**generator-team-services-extension** is [Yeoman](http://yeoman.io/) generator that create an extension for Visual Studio Team Services or Team Foundation Server.
Done.

2017-03-24 20:28 UTC, wpschaub commented on package.json
> +  "description": "Team Foundation Server and Team Services extension code generator",
Done

2017-03-24 20:29 UTC, wpschaub commented on README.md
> +﻿# Yeoman-extension-code-generator
Done

2017-03-24 20:33 UTC, wpschaub approved these changes
After making Will's changes I approve.

2017-03-27 13:38 UTC, willsmythe commented
Looks good to me!

2017-03-27 13:43 UTC, willsmythe approved these changes

2017-03-27 13:46 UTC, merged